// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqNpXFL4ZQNcHgA5qaNqEoruM-LiuHJlk',
    appId: '1:449000467635:web:63078d12f049c4b73c94c6',
    messagingSenderId: '449000467635',
    projectId: 'gupta-restaurant-66c89',
    authDomain: 'gupta-restaurant-66c89.firebaseapp.com',
    storageBucket: 'gupta-restaurant-66c89.firebasestorage.app',
    measurementId: 'G-WDDYWLR80G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcSFw06kJ98o3e0ZEj4uDvU6k6JuBnCRM',
    appId: '1:449000467635:android:7e8a5a90229a0c5f3c94c6',
    messagingSenderId: '449000467635',
    projectId: 'gupta-restaurant-66c89',
    storageBucket: 'gupta-restaurant-66c89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtDNUcGOnFI3ijFP5Q9RhpWmPo4dQg_6U',
    appId: '1:449000467635:ios:07bac85288d007533c94c6',
    messagingSenderId: '449000467635',
    projectId: 'gupta-restaurant-66c89',
    storageBucket: 'gupta-restaurant-66c89.firebasestorage.app',
    iosBundleId: 'com.example.guptaresturent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtDNUcGOnFI3ijFP5Q9RhpWmPo4dQg_6U',
    appId: '1:449000467635:ios:07bac85288d007533c94c6',
    messagingSenderId: '449000467635',
    projectId: 'gupta-restaurant-66c89',
    storageBucket: 'gupta-restaurant-66c89.firebasestorage.app',
    iosBundleId: 'com.example.guptaresturent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqNpXFL4ZQNcHgA5qaNqEoruM-LiuHJlk',
    appId: '1:449000467635:web:ca0ee6677b72c0f83c94c6',
    messagingSenderId: '449000467635',
    projectId: 'gupta-restaurant-66c89',
    authDomain: 'gupta-restaurant-66c89.firebaseapp.com',
    storageBucket: 'gupta-restaurant-66c89.firebasestorage.app',
    measurementId: 'G-WBEHZTWV1E',
  );
}
